code --install-extension aaron-bond.better-comments
code --install-extension aaronthomas.vscode-snazzy-operator
code --install-extension be5invis.vscode-custom-css
code --install-extension christian-kohler.npm-intellisense
code --install-extension danwahlin.angular2-snippets
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension davidbabel.vscode-simpler-icons
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension eg2.vscode-npm-script
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension Equinusocio.vsc-material-theme
code --install-extension fabiospampinato.vscode-monokai-night
code --install-extension file-icons.file-icons
code --install-extension GitHub.vscode-pull-request-github
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension HookyQR.beautify
code --install-extension idleberg.hopscotch
code --install-extension infinity1207.angular2-switcher
code --install-extension joaomoreno.github-sharp-theme
code --install-extension johnpapa.Angular2
code --install-extension LaurentTreguier.vscode-simple-icons
code --install-extension lonefy.vscode-JS-CSS-HTML-formatter
code --install-extension mauve.terraform
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension ms-python.python
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension oscarmcm.ocean-space
code --install-extension PeterJausovec.vscode-docker
code --install-extension philsinatra.popping-and-locking-vscode-black
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension rbbit.typescript-hero
code --install-extension reagankarnes.one-material-dark
code --install-extension redhat.java
code --install-extension robertohuertasm.vscode-icons
code --install-extension sidneys1.gitconfig
code --install-extension SintrumIT.theme-oceanic-next-italic
code --install-extension sldobri.daily
code --install-extension SonarSource.sonarlint-vscode
code --install-extension teabyii.ayu
code --install-extension Tyriar.sort-lines
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension waderyan.gitblame
code --install-extension whizkydee.material-palenight-theme
code --install-extension zhuangtongfa.Material-theme