code --install-extension DotJoshJohnson.xml
code --install-extension PKief.material-icon-theme
code --install-extension PeterJausovec.vscode-docker
code --install-extension SintrumIT.theme-oceanic-next-italic
code --install-extension Tyriar.sort-lines
code --install-extension aaron-bond.better-comments
code --install-extension aaronthomas.vscode-snazzy-operator
code --install-extension be5invis.vscode-custom-css
code --install-extension christian-kohler.npm-intellisense
code --install-extension danwahlin.angular2-snippets
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension idleberg.hopscotch
code --install-extension infinity1207.angular2-switcher
code --install-extension johnpapa.Angular2
code --install-extension lonefy.vscode-JS-CSS-HTML-formatter
code --install-extension ms-vscode.azure-account
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension pnp.polacode
code --install-extension rbbit.typescript-hero
code --install-extension redhat.java
code --install-extension sidneys1.gitconfig
code --install-extension teabyii.ayu
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension waderyan.gitblame
code --install-extension whizkydee.material-palenight-theme
code --install-extension zhuangtongfa.Material-theme
