code --install-extension 42Crunch.vscode-openapi
code --install-extension 4ops.terraform
code --install-extension aaron-bond.better-comments
code --install-extension adpyke.vscode-sql-formatter
code --install-extension be5invis.vscode-custom-css
code --install-extension christian-kohler.npm-intellisense
code --install-extension daylerees.rainglow
code --install-extension DotJoshJohnson.xml
code --install-extension eg2.vscode-npm-script
code --install-extension hashicorp.terraform
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension lonefy.vscode-JS-CSS-HTML-formatter
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension rbbit.typescript-hero
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension sidneys1.gitconfig
code --install-extension Tyriar.sort-lines
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension waderyan.gitblame
code --install-extension wwmyers.hackpot